config/routes.rb
Rails.application.routes.draw do

  resources :users, only: %w(show), param: :uid do
    resources :words, only: %w(index create update destroy), module: :users
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }
  devise_scope :user do
    root 'devise/sessions#new'
    get 'sign_in', to: 'devise/sessions#new'
  end

  post '/callback' => 'linebot#callback'

  get '/agreement', to: 'static_pages#agreement'
  get '/privacy', to: 'static_pages#privacy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,:rememberable, :trackable, :validatable, :omniauthable

  has_many :words, dependent: :destroy

  validates :words, length: { maximum: 100 }

  def set_values(omniauth)
    return if provider.to_s != omniauth['provider'].to_s || uid != omniauth['uid']
    credentials = omniauth['credentials']
    info = omniauth['info']

    access_token = credentials['refresh_token']
    access_secret = credentials['secret']
    credentials = credentials.to_json
    name = info['name']
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  validates :translation, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_words_path(resource.uid)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/linebot_controller.rb
class LinebotController < ApplicationController
  require 'line/bot'

  protect_from_forgery :except => [:callback]

  def client
    @client ||= Line::Bot::Client.new { |config|
      config.channel_secret = Rails.application.credentials[Rails.env.to_sym][:line][:message][:channel_secret]
      config.channel_token = Rails.application.credentials[Rails.env.to_sym][:line][:message][:channel_token]
    }
  end

  def callback
    message = LineMessage.new
    message.callback(request, client)
    head :ok
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def line
    basic_action
  end

  private

  def basic_action
    @omniauth = request.env['omniauth.auth']
    if @omniauth.present?
      @profile = User.where(provider: @omniauth['provider'], uid: @omniauth['uid']).first
      if @profile
        @profile.set_values(@omniauth)
        sign_in(:user, @profile)
        notice = 'ログインしました。'
      else
        @profile = User.new(provider: @omniauth['provider'], uid: @omniauth['uid'])
        @profile = current_user || User.create!(provider: @omniauth['provider'], uid: @omniauth['uid'], name: @omniauth['info']['name'], password: Devise.friendly_token[0, 20])
        @profile.set_values(@omniauth)
        sign_in(:user, @profile)
        notice = 'ユーザーが登録されました。'
      end
    end
    flash[:notice] = notice
    redirect_to user_words_path(@profile.uid)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def agreement; end

  def privacy; end
end

app/controllers/users/words_controller.rb
class Users::WordsController < ApplicationController
  before_action :set_word, only: %w(destroy update)
  before_action :authenticate_user!
  protect_from_forgery :except => [:update]

  def index
    @words = current_user.words.order(id: 'DESC')
  end

  def create
    word = current_user.words.new(name: params[:name], translation: params[:translation])
    word.translation = Translate.to_japanese(word.name) if word.translation.blank?
    if word.save
      redirect_to user_words_path
    else
      redirect_to user_words_path, status: 422
    end
  end

  def destroy
    if @word.destroy
      redirect_to user_words_path
    else
      # TODO: error message 表示
      redirect_to user_words_path, status: 422
    end
  end

  def update
    if @word.update(translation: params[:translation])
      redirect_to user_words_path
    else
      redirect_to user_words_path, status: 422
    end
  end

  private

  def set_word
    @word = Word.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer-nav.html.slim
nav#footer-nav
  ul.footer-nav__items
    li
      = link_to root_path
        = image_tag('list.png', alt: '', size: '30x30', class: 'footer-nav__icon')
        .footer-nav__text= '一覧'
    / TODO: 問題のアイコンの画像
    / li
    /   = link_to
    /     = image_tag('list.png', alt: '', size: '30x30', class: 'footer-nav__icon')
    /     .footer-nav__text= '問題'
    / li
    /   = link_to
    /     = image_tag('setting.png', alt: '', size: '30x30', class: 'footer-nav__icon')
    /     .footer-nav__text= '設定'
    li
      = link_to destroy_user_session_path, method: :delete
        = image_tag('logout.png', alt: '', size: '30x30', class: 'footer-nav__icon')
        .footer-nav__text= 'ログアウト'

app/views/layouts/_global_footer.html.slim
footer#footer
  .footer__inner
    ul.footer-rule__items
      li.footer-rule__item
        = link_to '利用規約', agreement_path
      li
        | /
      li.footer-rule__item
        = link_to 'privacy policy', privacy_path

app/views/layouts/_global_header.html.slim
header#header
  .header__inner
    =link_to root_path, class: 'header__title' do
      span.header__title--accent Re
      | :Tango

app/views/layouts/_sidenav.html.slim
nav#sidenav
  ul.sidenav__items
    / TODO: 問題追加
    / TODO: 設定追加
    / TODO: 選択されたものは色をアクセントカラーにする
    li= link_to '一覧'
    / li= link_to '問題'
    / li= link_to '設定'
    li= link_to 'ログアウト', destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Re:Tango
    meta[name="viewport" content="width=device-width,initial-scale=1.0"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/global_header' unless request.env['PATH_INFO'] == '/'
    main = yield
    = render 'layouts/global_footer' unless request.env['PATH_INFO'] == '/'
    = render 'layouts/footer-nav' unless request.env['PATH_INFO'] == '/'

app/views/static_pages/agreement.html.slim
section
  .p-static-pages
    h1
      | 利用規約
    p
      | この利用規約（以下，「本規約」といいます。）は，たくま（@t_fit_engineer）（以下，「当サービス提供者」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
    h2
      | 第1条（適用）
    ol
      li
        | 本規約は，ユーザーと当サービス提供者との間の本サービスの利用に関わる一切の関係に適用されるものとします。
      li
        | 当サービス提供者は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。
      li
        | 本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。
    h2
      | 第2条（利用登録）
    ol
      li
        | 本サービスにおいては，登録希望者が本規約に同意の上，当サービス提供者の定める方法によって利用登録を申請し，当サービス提供者がこれを承認することによって，利用登録が完了するものとします。
      li
        | 当サービス提供者は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
        ol
          li
            | 利用登録の申請に際して虚偽の事項を届け出た場合
          li
            | 本規約に違反したことがある者からの申請である場合
          li
            | その他，当サービス提供者が利用登録を相当でないと判断した場合
    h2
      | 第3条（利用料金および支払方法）
    ol
      li
        | ユーザーは，本サービスの有料部分の対価として，当サービス提供者が別途定め，本ウェブサイトに表示する利用料金を，当サービス提供者が指定する方法により支払うものとします。
      li
        | ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。
    h2
      | 第4条（禁止事項）
    p
      | ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
    ol
      li
        | 法令または公序良俗に違反する行為
      li
        | 犯罪行為に関連する行為
      li
        | 本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為
      li
        | 当サービス提供者，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為
      li
        | 本サービスによって得られた情報を商業的に利用する行為
      li
        | 当サービス提供者のサービスの運営を妨害するおそれのある行為
      li
        | 不正アクセスをし，またはこれを試みる行為
      li
        | 他のユーザーに関する個人情報等を収集または蓄積する行為
      li
        | 不正な目的を持って本サービスを利用する行為
      li
        | 本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為
      li
        | 他のユーザーに成りすます行為
      li
        | 当サービス提供者が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為
      li
        | 面識のない異性との出会いを目的とした行為
      li
        | 当サービス提供者のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為
      li
        | その他，当サービス提供者が不適切と判断する行為
    h2
      | 第5条（本サービスの提供の停止等）
    ol
      li
        | 当サービス提供者は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
        ol
          li
            | 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
          li
            | 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合
          li
            | コンピュータまたは通信回線等が事故により停止した場合
          li
            | その他，当サービス提供者が本サービスの提供が困難と判断した場合
      li
        | 当サービス提供者は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。
    h2
      | 第6条（利用制限および登録抹消）
    ol
      li
        | 当サービス提供者は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。
        ol
          li
            | 本規約のいずれかの条項に違反した場合
          li
            | 登録事項に虚偽の事実があることが判明した場合
          li
            | 料金等の支払債務の不履行があった場合
          li
            | 当サービス提供者からの連絡に対し，一定期間返答がない場合
          li
            | 本サービスについて，最終の利用から一定期間利用がない場合
          li
            | その他，当サービス提供者が本サービスの利用を適当でないと判断した場合
      li
        | 当サービス提供者は，本条に基づき当サービス提供者が行った行為によりユーザーに生じた損害について，一切の責任を負いません。
    h2
      | 第7条（退会）
    p
      | ユーザーは，当サービス提供者の定める退会手続により，本サービスから退会できるものとします。
    h2
      | 第8条（保証の否認および免責事項）
    ol
      li
        | 当サービス提供者は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
      li
        | 当サービス提供者は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当サービス提供者とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。
      li
        | 前項ただし書に定める場合であっても，当サービス提供者は，当サービス提供者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当サービス提供者またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当サービス提供者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
      li
        | 当サービス提供者は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
    h2
      | 第9条（サービス内容の変更等）
    p
      | 当サービス提供者は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
    h2
      | 第10条（利用規約の変更）
    p
      | 当サービス提供者は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。
    h2
      | 第11条（個人情報の取扱い）
    p
      | 当サービス提供者は，本サービスの利用によって取得する個人情報については，当サービス提供者「プライバシーポリシー」に従い適切に取り扱うものとします。
    h2
      | 第12条（通知または連絡）
    p
      | ユーザーと当サービス提供者との間の通知または連絡は，当サービス提供者の定める方法によって行うものとします。当サービス提供者は,ユーザーから,当サービス提供者が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。
    h2
      | 第13条（権利義務の譲渡の禁止）
    p
      | ユーザーは，当サービス提供者の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
    h2
      | 第14条（準拠法・裁判管轄）
    ol
      li
        | 本規約の解釈にあたっては，日本法を準拠法とします。
      li
        | 本サービスに関して紛争が生じた場合には，当サービス提供者の本店所在地を管轄する裁判所を専属的合意管轄とします。
    p
      | 以上
    p
      | 更新日：2020年6月4日

app/views/static_pages/privacy.html.slim
section
  .p-static-pages
    h1
      | プライバシーポリシー
    h2
      | 1. 基本方針
    p
      | たくま（@t_fit_engineer） (以下、「当サービス提供者」)は、個人情報の重要性を認識し、個人情報を保護することが社会的責務であると考え、個人情報に関する法令等を遵守し、当サービス提供者で取扱う個人情報の取得、利用、管理を適正に行います。
    h2
      | 2. 適用範囲
    p
      | 本プライバシーポリシーは、このウェブサイト上で提供するサービスにおいて、登録ユーザーの皆さま（以下，「ユーザー」といいます。）の個人情報もしくはそれに準ずる情報を取り扱う際に、当サービス提供者が遵守する方針を示したものです。

    h2
      | 3. 個人情報の取得と利用目的
    p
      | 当サービス提供者は、ユーザーから以下の情報をご提供いただきます。
    ol
      li
        | ユーザー：LINEアカウント名、LINEユーザーID
    p
      | また、当サービス提供者は、ユーザーからご提供いただく情報を以下の目的の範囲内において、利用します。ユーザーの同意なく、個人情報の収集や目的外の利用を行うことはありません。
    ol
      li
        | 当サービス提供者サービスの提供・運営のため
      li
        | ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
      li
        | ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当サービス提供者が提供する他のサービスの案内のメッセージを送付するため
      li
        | メンテナンス，重要なお知らせなど必要に応じたご連絡のため
      li
        | 利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
      li
        | ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
      li
        | 有料サービスにおいて，ユーザーに利用料金を請求するため
      li
        | 上記の利用目的に付随する目的
    h2
      | 4. 個人情報の管理
    p
      | 当サービス提供者は、ユーザーからご提供いただいた情報の管理について、以下を徹底します。
    ol
      li
        | 情報の正確性の確保
        p
          | ユーザーからご提供いただいた情報については、常に正確かつ最新の情報となるよう努めます。
      li
        | 安全管理措置
        p
          | 個人情報への不正アクセス・紛失・破損・改ざん・漏洩などを防止するため、セキュリティシステムの維持・管理体制の整備・社員教育の徹底等の必要な措置を講じ、安全対策を実施し個人情報の厳重な管理を行ないます。
      li
        | 委託先の監督
        p
          | 個人情報の取扱いを外部に委託する場合には、当サービス提供者の規程に基づき、用件を満たした委託先にのみ委託を行い、適切な管理を行います。
      li
        | 保存期間と廃棄
        p
          | ユーザーからご提供いただいた情報については、保存期間を設定し、保存期間終了後は廃棄します。
        p
          | また、保存期間内であっても、不要となった場合にはすみやかに廃棄します。
    h2
      | 5.個人情報の第三者への開示・提供の禁止
    p
      | 当サービス提供者は、ユーザーからご提供いただいた個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示いたしません。
    ol
      li
        | お客さまの同意がある場合
      li
        | ユーザーが希望されるサービスを行なうために当サービス提供者が業務を委託する業者に対して開示する場合
      li
        | 法令に基づき開示することが必要である場合
    h2
      | 6. 個人情報の開示・訂正・利用停止等
    p
      | 開示、訂正、利用停止等のお申し出があった場合には、当サービス提供者所定の方法に基づき対応致します。具体的な方法については、個別にご案内しますので、「7.問い合わせ先」に記載の受付窓口までお問い合わせください。
    h2
      | 7.法令、規範の遵守と見直し
    p
      | 当サービス提供者は、保有する個人情報に関して適用される日本の法令、その他規範を遵守するとともに、本プライバシーポリシーの内容を適宜見直し、その改善に努めます。
    h2
      | 8. 問い合わせ先
    p
      | 個人情報の取扱いに関しては、下記の受付窓口までメールにてお問い合わせください。
    p
      | takuma521521☆gmail.com
      br
      | ※迷惑メール対策のため、「☆」で表記しております。お問合わせの際は「☆」を半角の「@」に変更してご利用ください。
      p
        | 以上
      p
        | 更新日：2020年6月4日

app/views/users/books/words/index.html.slim
h1 単語帳

= form_with(url: user_book_words_path, local: true) do |form|
  table
    thead
      tr
        td
        td= form.label '単語', for: :english
        td= form.label '意味', for: :japanese
        td
    tbody
      tr
        td= form.submit value: '＋'
        td= form.text_field :name, id: :english, required: true
        td= form.text_field :translation, id: :japanese, required: true
table
  thead
    tr
      th
      th 単語
      th 意味
      th 正解数
      th 出題数
  tbody
    - @words.each do |word|
      tr
        td= link_to '-', user_book_word_path(current_user.uid, word.book_id, word), method: :delete
          / TODO: 編集できるようにする
        td= word.name
        td= word.translation
        td= word.correct_answer_count
        td= word.question_count
= link_to '単語帳一覧へ', user_books_path
= link_to 'logout', destroy_user_session_path, method: :delete

app/views/users/words/index.html.slim
= render 'layouts/sidenav'

section.p-words-section
  .p-words-wrapper

    - if flash[:notice]
      p= flash[:notice]

    - if @words.blank?
      p= '単語を追加してください。'

    .p-control-bar
      = form_with url: user_words_path, class: 'c-form p-add-form' do |form|
        =form.text_field :name, id: :english, required: true, class: 'p-add-form__input--en', placeholder: '単語を追加する'
        =form.submit value: '＋', class: 'p-add-form__submit', data: { disable_with: '..' }
    .p-words-table-wrapper
      table.p-words-table
        thead.p-words-table__thead
          tr
            th
            th 単語
            th 意味
        tbody.p-words-table__tbody
          - @words.each do |word|
            tr
              td= link_to '×', user_word_path(current_user.uid, word), method: :delete, remote: true
              td= word.name
              td.js-update-word data-json=word.id
                = word.translation